# Ruby のベースイメージを指定
FROM ruby:3.4.8

# 環境変数の設定
# 日本語対応
ENV LANG C.UTF-8
# タイムゾーンを日本に設定
ENV TZ Asia/Tokyo

# 必要なパッケージのインストール
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    vim \
    imagemagick \
    fonts-noto-cjk

# Corepackを有効にして、最新のYarnを使えるようにする。これにより、複雑なリポジトリ登録なしでyarnが使えるようになる。
RUN corepack enable

# アプリケーションディレクトリの作成
RUN mkdir /myapp
WORKDIR /myapp

# Bundlerのインストール
RUN gem install bundler

# アプリケーションのコードをコピー
COPY . /myapp