default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks_schedule: config/recurring.yml
  workers:
    - queues: "*"
      threads: 3
      polling_interval: 1

development:
  <<: *default

production:
  <<: *default
