# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
production:
  scheduled_push_job:
    class: ScheduledPushJob
    schedule: "0 23 * * *"  # 毎日朝8時JST（UTC 23:00）
    queue: default

development:
  scheduled_push_job:
    class: ScheduledPushJob
    schedule: "*/10 * * * *"   # 動作確認用：10分実行
    queue: default